FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

USER 1001

EXPOSE 8080

CMD ["python","recommendation_server.py"]
