FROM registry.access.redhat.com/ubi9/nodejs-18

WORKDIR /app

COPY package*.json ./

USER root
RUN chown -R 1001:0 /app

USER 1001
RUN npm install --omit=dev

COPY . .

EXPOSE 50051

CMD ["node", "server.js"]
